package Pojo;




/**
 * Adminler generated by hbm2java
 */
public class Adminler  extends DataType{

     private Calisanlar calisanlar;
     private String username;
     private String password;

    public Adminler() {
    }

    public Adminler(Calisanlar calisanlar, String username, String password) {
       this.calisanlar = calisanlar;
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Calisanlar getCalisanlar() {
        return this.calisanlar;
    }
    
    public void setCalisanlar(Calisanlar calisanlar) {
        this.calisanlar = calisanlar;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }






}


