package Pojo;



import java.util.HashSet;
import java.util.Set;

/**
 * Calisanlar generated by hbm2java
 */
public class Calisanlar  extends DataType{

     private String ad;
     private String soyad;
     private String departman;
     private String maas;
     private byte[] image;
     private Set adminlers = new HashSet(0);

    public Calisanlar() {
    }

	
    public Calisanlar(String ad, String soyad, String departman, String maas, byte[] image) {
        this.ad = ad;
        this.soyad = soyad;
        this.departman = departman;
        this.maas = maas;
        this.image = image;
    }
    public Calisanlar(String ad, String soyad, String departman, String maas, byte[] image, Set adminlers) {
       this.ad = ad;
       this.soyad = soyad;
       this.departman = departman;
       this.maas = maas;
       this.image = image;
       this.adminlers = adminlers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }
    public String getSoyad() {
        return this.soyad;
    }
    
    public void setSoyad(String soyad) {
        this.soyad = soyad;
    }
    public String getDepartman() {
        return this.departman;
    }
    
    public void setDepartman(String departman) {
        this.departman = departman;
    }
    public String getMaas() {
        return this.maas;
    }
    
    public void setMaas(String maas) {
        this.maas = maas;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public Set getAdminlers() {
        return this.adminlers;
    }
    
    public void setAdminlers(Set adminlers) {
        this.adminlers = adminlers;
    }

    @Override
    public String toString() {
        return ad + " " + soyad;
    }

    



}


